### ISSUE TITLE
Docker compose up (installation) fails

### ISSUE THREAD

**Issue by KrustyDerClown** [MycroftAI/mimic-recording-studio#102]
This occurs under windows and linux

```
(66/66) Installing subversion (1.9.7-r0)
Executing subversion-1.9.7-r0.pre-install
Executing busybox-1.26.2-r11.trigger
OK: 326 MiB in 89 packages
Removing intermediate container a091584b1588
 ---> 10e598fcf691
Step 6/7 : RUN pip install -r requirements.txt
 ---> Running in c26e696a0816
Collecting flask (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/cd/77/59df23681f4fd19b7cbbb5e92484d46ad587554f5d490f33ef907e456132/Flask-2.0.3-py3-none-any.whl (95kB)
Collecting flask-cors (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/db/84/901e700de86604b1c4ef4b57110d4e947c218b9997adf5d38fa7da493bce/Flask_Cors-3.0.10-py2.py3-none-any.whl
Collecting peewee (from -r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/a9/50/1dd5ea74c559df4afb8391f8d05f0fec685dbe8effba13bb9072901eb288/peewee-3.16.2.tar.gz (2.9MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  Complete output from command /usr/local/bin/python /usr/local/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp6f678wxj:
  /tmp/tmp_pw_sqlite3_zzc8ptgy/test_pw_sqlite3.c:1:21: fatal error: sqlite3.h: No such file or directory
   #include <sqlite3.h>
                       ^
  compilation terminated.
  setup.py:110: UserWarning: Could not find libsqlite3, SQLite extensions will not be built.
    warnings.warn('Could not find libsqlite3, SQLite extensions will not '
  unable to compile sqlite3 C extensions - missing headers?
  Traceback (most recent call last):
    File "/usr/local/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
      main()
    File "/usr/local/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 54, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-hov778t4/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 163, in get_requires_for_build_wheel
      config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-hov778t4/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 143, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-hov778t4/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 196, in <module>
      _do_setup(extension_support, sqlite_extension_support)
    File "setup.py", line 150, in _do_setup
      version=__import__('peewee').__version__,
  ModuleNotFoundError: No module named 'peewee'
  
  ----------------------------------------
Command "/usr/local/bin/python /usr/local/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp6f678wxj" failed with error code 1 in /tmp/pip-install-q6tw5tww/peewee
You are using pip version 19.0.1, however version 21.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
ERROR: Service 'backend' failed to build: The command '/bin/sh -c pip install -r requirements.txt' returned a non-zero code: 1
```

**Comment by mrmorganmurphy** [comment]
Receiving the same error.
Ubuntu 23.04
Kernel Linux 6.2.0-20-generic

```
Building backend
Sending build context to Docker daemon  4.733MB
Step 1/7 : FROM python:3.6-alpine3.6
 ---> 316214a5f0e2
Step 2/7 : COPY requirements.txt /src/
 ---> Using cache
 ---> e3ad39ddec82
Step 3/7 : WORKDIR /src
 ---> Using cache
 ---> 70765b0dcf29
Step 4/7 : RUN apk update
 ---> Using cache
 ---> f8d17c32427b
Step 5/7 : RUN apk add ffmpeg make automake gcc g++ subversion python3-dev
 ---> Using cache
 ---> 5946c8240f1d
Step 6/7 : RUN pip install -r requirements.txt
 ---> Running in d0ae95410bf2
Collecting flask (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/cd/77/59df23681f4fd19b7cbbb5e92484d46ad587554f5d490f33ef907e456132/Flask-2.0.3-py3-none-any.whl (95kB)
Collecting flask-cors (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/db/84/901e700de86604b1c4ef4b57110d4e947c218b9997adf5d38fa7da493bce/Flask_Cors-3.0.10-py2.py3-none-any.whl
Collecting peewee (from -r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/a9/50/1dd5ea74c559df4afb8391f8d05f0fec685dbe8effba13bb9072901eb288/peewee-3.16.2.tar.gz (2.9MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  Complete output from command /usr/local/bin/python /usr/local/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp5skr5iex:
  /tmp/tmp_pw_sqlite3_v2_a2aa1/test_pw_sqlite3.c:1:21: fatal error: sqlite3.h: No such file or directory
   #include <sqlite3.h>
                       ^
  compilation terminated.
  setup.py:110: UserWarning: Could not find libsqlite3, SQLite extensions will not be built.
    warnings.warn('Could not find libsqlite3, SQLite extensions will not '
  unable to compile sqlite3 C extensions - missing headers?
  Traceback (most recent call last):
    File "/usr/local/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
      main()
    File "/usr/local/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 54, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-js_cbb3_/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 163, in get_requires_for_build_wheel
      config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-js_cbb3_/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 143, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-js_cbb3_/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 196, in <module>
      _do_setup(extension_support, sqlite_extension_support)
    File "setup.py", line 150, in _do_setup
      version=__import__('peewee').__version__,
  ModuleNotFoundError: No module named 'peewee'
  
  ----------------------------------------
Command "/usr/local/bin/python /usr/local/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp5skr5iex" failed with error code 1 in /tmp/pip-install-fw7cc9vo/peewee
You are using pip version 19.0.1, however version 21.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
The command '/bin/sh -c pip install -r requirements.txt' returned a non-zero code: 1
ERROR: Service 'backend' failed to build : Build failed
```

**Comment by mrmorganmurphy** [comment]
Pull  #101 appears to have a fix in place.

**Comment by mxk1011** [comment]
Pull #101 solved it for me

**Comment by 7ae** [comment]
Pull #101 works for me too. Here are the steps I followed:

1. `git clone https://github.com/pluja/mimic-recording-studio.git`
2. `cd mimic-recording-studio`
3. `docker-compose up` or `sudo docker-compose up`
4. `http://localhost:3000/`
